/** Keep in sync with src/games/templates/catalog.ts */
export const TEMPLATE_ENGINES: Record<string, string> = {
  forest_catch: "falling_catch",
  bamboo_path: "falling_catch",
  beach_swipe: "swipe_wind",
  coast_wind: "swipe_wind",
  city_crosswalk: "hold_crosswalk",
  urban_hold: "hold_crosswalk",
  night_firefly: "drag_jar",
  garden_jar: "drag_jar",
  market_swarm: "falling_swarm",
  street_food: "falling_swarm",
  temple_rhythm: "rhythm_tap",
  shrine_bell: "rhythm_tap",
  rain_shield: "falling_tap_clear",
  storm_clear: "falling_tap_clear",
  metro_lane: "lanes_vertical",
  train_rush: "lanes_vertical",
  tram_collect: "tram_sides",
  harbor_tram: "tram_sides",
  motorbike_sides: "tram_sides",
  alley_weave: "lanes_vertical",
  snow_shield: "falling_tap_clear",
  winter_clear: "falling_catch",
  desert_snap: "falling_catch",
  mirage_photo: "falling_catch",
  festival_swarm: "falling_swarm",
  lantern_rain: "falling_swarm",
  cafe_balance: "rhythm_tap",
  coffee_rhythm: "rhythm_tap",
  museum_snap: "falling_catch",
  gallery_pop: "photo_pop",
  mountain_hold: "hold_crosswalk",
  summit_flag: "hold_crosswalk",
  river_drag: "drag_jar",
  lake_catch: "falling_catch",
  wildlife_snap: "falling_catch",
  safari_pop: "photo_pop",
  diary_quiz: "text_quiz",
  landmark_quiz: "text_quiz",
  food_quiz: "text_quiz",
  caption_fill: "text_fill",
  diary_fill: "text_fill",
  mood_fill: "text_fill",
  itinerary_order: "text_order",
  taste_order: "text_order",
  journey_choice: "text_choice",
  detour_choice: "text_choice",
  hostel_choice: "text_choice",
  market_bargain: "text_choice",
};

export function engineForTemplate(templateId: string): string {
  return TEMPLATE_ENGINES[templateId] ?? "falling_catch";
}
